# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='img', verbose_name='첨부파일')),
            ],
        ),
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='이름')),
                ('age', models.IntegerField(null=True, verbose_name='나이')),
                ('burth', models.DateTimeField(null=True, verbose_name='생년월일')),
                ('address', models.CharField(blank=True, max_length=40, null=True, verbose_name='요약')),
                ('phone', models.CharField(blank=True, help_text="'-'없이 입력하세요 ex) 01012341234", max_length=11, null=True, verbose_name='연락처')),
                ('location', models.CharField(max_length=10, null=True, verbose_name='사고위치')),
                ('symptom', models.CharField(max_length=20, null=True, verbose_name='증상')),
                ('cause', models.CharField(max_length=30, null=True, verbose_name='원인')),
                ('content', models.TextField(null=True, verbose_name='구조 내용')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='rescue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Rescue', verbose_name='구조'),
        ),
    ]
