# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20170624_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescue',
            name='date',
            field=models.DateField(default=datetime.date(2017, 7, 1), verbose_name='날짜'),
        ),
    ]
